### ISSUE TITLE
Allow users to add sensors to existing machines

### ISSUE THREAD

**Issue by KimberleyEvans-Parker** [se761group2/industry-4#12]
As a technician, I want to be able to add new sensors to a machine in the system so that I am not limited to the ones currently available

**Acceptance Criteria**

 - If the user is logged in, they can add a new sensor to an existing machine using a text field, entering the machine ID and Sensor name
 - Once this sensor is added, it can be viewed like the others from the machines page within that machine

**Is your feature request related to a problem? Please describe.**
Without this no sensors can be added to the existing machines without technical support from a developer. This would mean to keep the app functional in a meaningful and helpful way, constant maintenance would be required.

**Describe the solution you'd like**
There should be a button in the relevant place (e.g. on the machine sensors overview page) which allows users to add sensors to that machine which can then be tracked.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by George-E-M** [comment]
Do we require a specific issue for allowing users to add new machines. If not should this issue be expanded to include that functionality, or should this issue be expanded to specify adding new machines, not sensors.

**Comment by George-E-M** [comment]
Two separate issues, change this one so it specifies adding to an existing machine
