### ISSUE TITLE
Download data as a file

### ISSUE THREAD

**Issue by margeobur** [se761group2/industry-4#15]
As a technician,
I want to download historical data for one or more sensors as a file,
So that I can inspect it in other tools (e.g. Excel)

**Acceptance Criteria**
 - User can clearly see how to initiate download
 - User can select which sensors they want to download the data for
 - Confirming initiates download
 - User can select a time frame of the data they wish to download

**Related Problem**
The PO requested this feature explicitly. They would like historical data to be downloadable so that researchers and technicians can use it for various purposes other than real-time health monitoring

**Suggested Design**
Button brings up selection pop-up to choose which sensors / machines to download data from

Start by offering CSV as the file format (others can be added later)

Need to decide how far back they can download (probably start with since the beginning of the signal's life

**Comment by George-E-M** [comment]
Should this issue be expanded to allow users to select time frames to download the data between.
