### ISSUE TITLE
Persisting Data

### ISSUE THREAD

**Issue by FrankWangma** [se761group2/industry-4#16]
As a technician, I would like to store incoming data in a database, so that it can be used for historical data

**Acceptance Criteria**

 - Incoming data from the machines need to be stored in some kind of persistent database
 - The data needs to be processed and stored in a readable format, so raw data is not stored in the database

**Is your feature request related to a problem? Please describe.**
The PO mentioned that they want both historical and downloadable data to check for anomalies that have previously happened. They also want this to help see any trends in the defects. 

**Describe the solution you'd like**
A persistent database, which is stored in the cloud so that any user can access it at any time. This database needs to be accessible through the application, and the constant flow of data from the machine needs to be processed into a readable format (likely just large tables of information representing each machine).

**Describe alternatives you've considered**
N/A

**Additional context**
Split from #23

**Comment by margeobur** [comment]
Technically this hasn't been done if you go by the description - this covered storing incoming data from the ingestor but the linked PR focuses on the GraphQL API. I'll split off an issue that specifically covers the getting info from the backend as well as adding info from the frontend  (info about new machines, sensors and users)
