### ISSUE TITLE
Allow users to add machines

### ISSUE THREAD

**Issue by George-E-M** [se761group2/industry-4#26]
As a technician, I want to add new machines to the application so that I can track their sensor data

**Acceptance Criteria**
 - If a user is logged in they can add a new machine for the application to track
 - When this machine is being added, the user can associate any number of sensors related to the machine
 - Once this machine is added, it can be viewed like the others from the overview page

**Is your feature request related to a problem? Please describe.**
Without this no machines can be added to the application without technical support from a developer. This would mean to keep the app functional in a meaningful and helpful way, constant maintenance would be required.

**Describe the solution you'd like**
There should be a button in the relevant place (e.g. on the machine overview page or profile page) which allows users to add sensors to that machine which can then be tracked

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by margeobur** [comment]
Partially implemented by #40
