### ISSUE TITLE
Log in/Register

### ISSUE THREAD

**Issue by AlexanderTheGrape** [se761group2/industry-4#6]
As a user, I want to log in, so that I can see the machine data relevant to me.

**Acceptance Criteria**

 - Be able to register
 - Be able to log in
 - Using an incorrect username/password prevents getting to the profile/data pages
 - You must be logged in to see the profile/data pages
- Admin Accounts?

**Is your feature request related to a problem? Please describe.**
You should only be able to see what's relevant to you, and users should have the confidence that others can't see their data. Furthermore we need a way of authenticating users.

**Describe the solution you'd like**
A user must be able to log in using username and password. This username and password combination should not be hard-coded (i.e. actual combinations must be stored in a sort of database and checked).

**Describe alternatives you've considered**
No alternatives considered.

**Additional context**
There is a google plugin of sorts (can't remember the name), which will help speed up set up.

**Comment by George-E-M** [comment]
Should this issue refer to creating a specific login page or is it okay to just leave it as is?
