### ISSUE TITLE
Sending Notifications to Users

### ISSUE THREAD

**Issue by FrankWangma** [se761group2/industry-4#7]
As a Technician, I want to receive notifications from the application so that I can be warned whenever defects are detected

**Acceptance Criteria**

 - User is notified by the application that there is a defect in one or more of the machines
 - The notification given is an external notification, outside of the app
 - The notification provides some context about the issue
 - The notification takes the user to the report within the application

**Is your feature request related to a problem? Please describe.**
Technicians need a way of getting notified that there are issues with the machines. This should happen even if the technicians do not have the app/website open.

**Describe the solution you'd like**
A way of sending the technicians a notification through Email that an issue was detected with one or more of the machines. Such notification needs to be slightly detailed, with very important information displayed within the notification. It also requires a link to the report within the application

**Describe alternatives you've considered**
Alternatives to sending the Email, we could use SMS or push notifications to be sent to the user

**Additional context**
Child of #5

**Comment by George-E-M** [comment]
The PO seemed quite insistent on SMS notifications, so we may want to add that as part of the acceptance criteria.

**Comment by George-E-M** [comment]
Leave the acceptance criteria for now and try to convince the PO otherwise.
